(cl:defpackage unity_msgs-srv
  (:use )
  (:export
   "IMGSERV"
   "<IMGSERV-REQUEST>"
   "IMGSERV-REQUEST"
   "<IMGSERV-RESPONSE>"
   "IMGSERV-RESPONSE"
   "POSE"
   "<POSE-REQUEST>"
   "POSE-REQUEST"
   "<POSE-RESPONSE>"
   "POSE-RESPONSE"
   "POSITION"
   "<POSITION-REQUEST>"
   "POSITION-REQUEST"
   "<POSITION-RESPONSE>"
   "POSITION-RESPONSE"
  ))

