(cl:defpackage unity_msgs-msg
  (:use )
  (:export
   "<ARMPOSE>"
   "ARMPOSE"
   "<ARMTARGET>"
   "ARMTARGET"
   "<CAMIMGS>"
   "CAMIMGS"
   "<ORDERPICKERCAMERAROTATION>"
   "ORDERPICKERCAMERAROTATION"
   "<ORDERPICKERDIRECTION>"
   "ORDERPICKERDIRECTION"
   "<ORDERPICKERLIFTER>"
   "ORDERPICKERLIFTER"
   "<ORDERPICKERPOSITION>"
   "ORDERPICKERPOSITION"
   "<ORDERPICKERVELOCITY>"
   "ORDERPICKERVELOCITY"
  ))

