// Generated by gencpp from file unity_msgs/GripperSuck.msg
// DO NOT EDIT!


#ifndef UNITY_MSGS_MESSAGE_GRIPPERSUCK_H
#define UNITY_MSGS_MESSAGE_GRIPPERSUCK_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace unity_msgs
{
template <class ContainerAllocator>
struct GripperSuck_
{
  typedef GripperSuck_<ContainerAllocator> Type;

  GripperSuck_()
    : suck(0.0)  {
    }
  GripperSuck_(const ContainerAllocator& _alloc)
    : suck(0.0)  {
  (void)_alloc;
    }



   typedef float _suck_type;
  _suck_type suck;





  typedef boost::shared_ptr< ::unity_msgs::GripperSuck_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::unity_msgs::GripperSuck_<ContainerAllocator> const> ConstPtr;

}; // struct GripperSuck_

typedef ::unity_msgs::GripperSuck_<std::allocator<void> > GripperSuck;

typedef boost::shared_ptr< ::unity_msgs::GripperSuck > GripperSuckPtr;
typedef boost::shared_ptr< ::unity_msgs::GripperSuck const> GripperSuckConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::unity_msgs::GripperSuck_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::unity_msgs::GripperSuck_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::unity_msgs::GripperSuck_<ContainerAllocator1> & lhs, const ::unity_msgs::GripperSuck_<ContainerAllocator2> & rhs)
{
  return lhs.suck == rhs.suck;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::unity_msgs::GripperSuck_<ContainerAllocator1> & lhs, const ::unity_msgs::GripperSuck_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace unity_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::unity_msgs::GripperSuck_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::unity_msgs::GripperSuck_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::unity_msgs::GripperSuck_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::unity_msgs::GripperSuck_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::unity_msgs::GripperSuck_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::unity_msgs::GripperSuck_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::unity_msgs::GripperSuck_<ContainerAllocator> >
{
  static const char* value()
  {
    return "99e58236a92fed374f4db00fc52a88ea";
  }

  static const char* value(const ::unity_msgs::GripperSuck_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x99e58236a92fed37ULL;
  static const uint64_t static_value2 = 0x4f4db00fc52a88eaULL;
};

template<class ContainerAllocator>
struct DataType< ::unity_msgs::GripperSuck_<ContainerAllocator> >
{
  static const char* value()
  {
    return "unity_msgs/GripperSuck";
  }

  static const char* value(const ::unity_msgs::GripperSuck_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::unity_msgs::GripperSuck_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float32 suck\n"
;
  }

  static const char* value(const ::unity_msgs::GripperSuck_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::unity_msgs::GripperSuck_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.suck);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct GripperSuck_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::unity_msgs::GripperSuck_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::unity_msgs::GripperSuck_<ContainerAllocator>& v)
  {
    s << indent << "suck: ";
    Printer<float>::stream(s, indent + "  ", v.suck);
  }
};

} // namespace message_operations
} // namespace ros

#endif // UNITY_MSGS_MESSAGE_GRIPPERSUCK_H
