// Generated by gencpp from file unity_msgs/Imgserv.msg
// DO NOT EDIT!


#ifndef UNITY_MSGS_MESSAGE_IMGSERV_H
#define UNITY_MSGS_MESSAGE_IMGSERV_H

#include <ros/service_traits.h>


#include <unity_msgs/ImgservRequest.h>
#include <unity_msgs/ImgservResponse.h>


namespace unity_msgs
{

struct Imgserv
{

typedef ImgservRequest Request;
typedef ImgservResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct Imgserv
} // namespace unity_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::unity_msgs::Imgserv > {
  static const char* value()
  {
    return "2756544b56553ab47e7b3ef7356d02a3";
  }

  static const char* value(const ::unity_msgs::Imgserv&) { return value(); }
};

template<>
struct DataType< ::unity_msgs::Imgserv > {
  static const char* value()
  {
    return "unity_msgs/Imgserv";
  }

  static const char* value(const ::unity_msgs::Imgserv&) { return value(); }
};


// service_traits::MD5Sum< ::unity_msgs::ImgservRequest> should match
// service_traits::MD5Sum< ::unity_msgs::Imgserv >
template<>
struct MD5Sum< ::unity_msgs::ImgservRequest>
{
  static const char* value()
  {
    return MD5Sum< ::unity_msgs::Imgserv >::value();
  }
  static const char* value(const ::unity_msgs::ImgservRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::unity_msgs::ImgservRequest> should match
// service_traits::DataType< ::unity_msgs::Imgserv >
template<>
struct DataType< ::unity_msgs::ImgservRequest>
{
  static const char* value()
  {
    return DataType< ::unity_msgs::Imgserv >::value();
  }
  static const char* value(const ::unity_msgs::ImgservRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::unity_msgs::ImgservResponse> should match
// service_traits::MD5Sum< ::unity_msgs::Imgserv >
template<>
struct MD5Sum< ::unity_msgs::ImgservResponse>
{
  static const char* value()
  {
    return MD5Sum< ::unity_msgs::Imgserv >::value();
  }
  static const char* value(const ::unity_msgs::ImgservResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::unity_msgs::ImgservResponse> should match
// service_traits::DataType< ::unity_msgs::Imgserv >
template<>
struct DataType< ::unity_msgs::ImgservResponse>
{
  static const char* value()
  {
    return DataType< ::unity_msgs::Imgserv >::value();
  }
  static const char* value(const ::unity_msgs::ImgservResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // UNITY_MSGS_MESSAGE_IMGSERV_H
