// Generated by gencpp from file unity_msgs/OrderPickerVelocity.msg
// DO NOT EDIT!


#ifndef UNITY_MSGS_MESSAGE_ORDERPICKERVELOCITY_H
#define UNITY_MSGS_MESSAGE_ORDERPICKERVELOCITY_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace unity_msgs
{
template <class ContainerAllocator>
struct OrderPickerVelocity_
{
  typedef OrderPickerVelocity_<ContainerAllocator> Type;

  OrderPickerVelocity_()
    : orderPickerSpeed(0.0)  {
    }
  OrderPickerVelocity_(const ContainerAllocator& _alloc)
    : orderPickerSpeed(0.0)  {
  (void)_alloc;
    }



   typedef float _orderPickerSpeed_type;
  _orderPickerSpeed_type orderPickerSpeed;





  typedef boost::shared_ptr< ::unity_msgs::OrderPickerVelocity_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::unity_msgs::OrderPickerVelocity_<ContainerAllocator> const> ConstPtr;

}; // struct OrderPickerVelocity_

typedef ::unity_msgs::OrderPickerVelocity_<std::allocator<void> > OrderPickerVelocity;

typedef boost::shared_ptr< ::unity_msgs::OrderPickerVelocity > OrderPickerVelocityPtr;
typedef boost::shared_ptr< ::unity_msgs::OrderPickerVelocity const> OrderPickerVelocityConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::unity_msgs::OrderPickerVelocity_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::unity_msgs::OrderPickerVelocity_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::unity_msgs::OrderPickerVelocity_<ContainerAllocator1> & lhs, const ::unity_msgs::OrderPickerVelocity_<ContainerAllocator2> & rhs)
{
  return lhs.orderPickerSpeed == rhs.orderPickerSpeed;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::unity_msgs::OrderPickerVelocity_<ContainerAllocator1> & lhs, const ::unity_msgs::OrderPickerVelocity_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace unity_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::unity_msgs::OrderPickerVelocity_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::unity_msgs::OrderPickerVelocity_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::unity_msgs::OrderPickerVelocity_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::unity_msgs::OrderPickerVelocity_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::unity_msgs::OrderPickerVelocity_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::unity_msgs::OrderPickerVelocity_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::unity_msgs::OrderPickerVelocity_<ContainerAllocator> >
{
  static const char* value()
  {
    return "b771032ad1d53adf5c692218acbd5c7b";
  }

  static const char* value(const ::unity_msgs::OrderPickerVelocity_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xb771032ad1d53adfULL;
  static const uint64_t static_value2 = 0x5c692218acbd5c7bULL;
};

template<class ContainerAllocator>
struct DataType< ::unity_msgs::OrderPickerVelocity_<ContainerAllocator> >
{
  static const char* value()
  {
    return "unity_msgs/OrderPickerVelocity";
  }

  static const char* value(const ::unity_msgs::OrderPickerVelocity_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::unity_msgs::OrderPickerVelocity_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float32 orderPickerSpeed\n"
;
  }

  static const char* value(const ::unity_msgs::OrderPickerVelocity_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::unity_msgs::OrderPickerVelocity_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.orderPickerSpeed);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct OrderPickerVelocity_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::unity_msgs::OrderPickerVelocity_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::unity_msgs::OrderPickerVelocity_<ContainerAllocator>& v)
  {
    s << indent << "orderPickerSpeed: ";
    Printer<float>::stream(s, indent + "  ", v.orderPickerSpeed);
  }
};

} // namespace message_operations
} // namespace ros

#endif // UNITY_MSGS_MESSAGE_ORDERPICKERVELOCITY_H
