// Generated by gencpp from file unity_msgs/OrderPickerDirection.msg
// DO NOT EDIT!


#ifndef UNITY_MSGS_MESSAGE_ORDERPICKERDIRECTION_H
#define UNITY_MSGS_MESSAGE_ORDERPICKERDIRECTION_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace unity_msgs
{
template <class ContainerAllocator>
struct OrderPickerDirection_
{
  typedef OrderPickerDirection_<ContainerAllocator> Type;

  OrderPickerDirection_()
    : orderPickerDirection(0.0)  {
    }
  OrderPickerDirection_(const ContainerAllocator& _alloc)
    : orderPickerDirection(0.0)  {
  (void)_alloc;
    }



   typedef float _orderPickerDirection_type;
  _orderPickerDirection_type orderPickerDirection;





  typedef boost::shared_ptr< ::unity_msgs::OrderPickerDirection_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::unity_msgs::OrderPickerDirection_<ContainerAllocator> const> ConstPtr;

}; // struct OrderPickerDirection_

typedef ::unity_msgs::OrderPickerDirection_<std::allocator<void> > OrderPickerDirection;

typedef boost::shared_ptr< ::unity_msgs::OrderPickerDirection > OrderPickerDirectionPtr;
typedef boost::shared_ptr< ::unity_msgs::OrderPickerDirection const> OrderPickerDirectionConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::unity_msgs::OrderPickerDirection_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::unity_msgs::OrderPickerDirection_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::unity_msgs::OrderPickerDirection_<ContainerAllocator1> & lhs, const ::unity_msgs::OrderPickerDirection_<ContainerAllocator2> & rhs)
{
  return lhs.orderPickerDirection == rhs.orderPickerDirection;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::unity_msgs::OrderPickerDirection_<ContainerAllocator1> & lhs, const ::unity_msgs::OrderPickerDirection_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace unity_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::unity_msgs::OrderPickerDirection_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::unity_msgs::OrderPickerDirection_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::unity_msgs::OrderPickerDirection_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::unity_msgs::OrderPickerDirection_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::unity_msgs::OrderPickerDirection_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::unity_msgs::OrderPickerDirection_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::unity_msgs::OrderPickerDirection_<ContainerAllocator> >
{
  static const char* value()
  {
    return "83553efb863f0e36f94f0d60ee9c10ce";
  }

  static const char* value(const ::unity_msgs::OrderPickerDirection_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x83553efb863f0e36ULL;
  static const uint64_t static_value2 = 0xf94f0d60ee9c10ceULL;
};

template<class ContainerAllocator>
struct DataType< ::unity_msgs::OrderPickerDirection_<ContainerAllocator> >
{
  static const char* value()
  {
    return "unity_msgs/OrderPickerDirection";
  }

  static const char* value(const ::unity_msgs::OrderPickerDirection_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::unity_msgs::OrderPickerDirection_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float32 orderPickerDirection\n"
;
  }

  static const char* value(const ::unity_msgs::OrderPickerDirection_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::unity_msgs::OrderPickerDirection_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.orderPickerDirection);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct OrderPickerDirection_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::unity_msgs::OrderPickerDirection_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::unity_msgs::OrderPickerDirection_<ContainerAllocator>& v)
  {
    s << indent << "orderPickerDirection: ";
    Printer<float>::stream(s, indent + "  ", v.orderPickerDirection);
  }
};

} // namespace message_operations
} // namespace ros

#endif // UNITY_MSGS_MESSAGE_ORDERPICKERDIRECTION_H
