// Generated by gencpp from file unity_msgs/Pose.msg
// DO NOT EDIT!


#ifndef UNITY_MSGS_MESSAGE_POSE_H
#define UNITY_MSGS_MESSAGE_POSE_H

#include <ros/service_traits.h>


#include <unity_msgs/PoseRequest.h>
#include <unity_msgs/PoseResponse.h>


namespace unity_msgs
{

struct Pose
{

typedef PoseRequest Request;
typedef PoseResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct Pose
} // namespace unity_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::unity_msgs::Pose > {
  static const char* value()
  {
    return "b83998b949202c6834b3ab9d4bd151b4";
  }

  static const char* value(const ::unity_msgs::Pose&) { return value(); }
};

template<>
struct DataType< ::unity_msgs::Pose > {
  static const char* value()
  {
    return "unity_msgs/Pose";
  }

  static const char* value(const ::unity_msgs::Pose&) { return value(); }
};


// service_traits::MD5Sum< ::unity_msgs::PoseRequest> should match
// service_traits::MD5Sum< ::unity_msgs::Pose >
template<>
struct MD5Sum< ::unity_msgs::PoseRequest>
{
  static const char* value()
  {
    return MD5Sum< ::unity_msgs::Pose >::value();
  }
  static const char* value(const ::unity_msgs::PoseRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::unity_msgs::PoseRequest> should match
// service_traits::DataType< ::unity_msgs::Pose >
template<>
struct DataType< ::unity_msgs::PoseRequest>
{
  static const char* value()
  {
    return DataType< ::unity_msgs::Pose >::value();
  }
  static const char* value(const ::unity_msgs::PoseRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::unity_msgs::PoseResponse> should match
// service_traits::MD5Sum< ::unity_msgs::Pose >
template<>
struct MD5Sum< ::unity_msgs::PoseResponse>
{
  static const char* value()
  {
    return MD5Sum< ::unity_msgs::Pose >::value();
  }
  static const char* value(const ::unity_msgs::PoseResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::unity_msgs::PoseResponse> should match
// service_traits::DataType< ::unity_msgs::Pose >
template<>
struct DataType< ::unity_msgs::PoseResponse>
{
  static const char* value()
  {
    return DataType< ::unity_msgs::Pose >::value();
  }
  static const char* value(const ::unity_msgs::PoseResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // UNITY_MSGS_MESSAGE_POSE_H
