// Generated by gencpp from file unity_msgs/PoseResponse.msg
// DO NOT EDIT!


#ifndef UNITY_MSGS_MESSAGE_POSERESPONSE_H
#define UNITY_MSGS_MESSAGE_POSERESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <unity_msgs/ArmPose.h>

namespace unity_msgs
{
template <class ContainerAllocator>
struct PoseResponse_
{
  typedef PoseResponse_<ContainerAllocator> Type;

  PoseResponse_()
    : output()  {
    }
  PoseResponse_(const ContainerAllocator& _alloc)
    : output(_alloc)  {
  (void)_alloc;
    }



   typedef  ::unity_msgs::ArmPose_<ContainerAllocator>  _output_type;
  _output_type output;





  typedef boost::shared_ptr< ::unity_msgs::PoseResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::unity_msgs::PoseResponse_<ContainerAllocator> const> ConstPtr;

}; // struct PoseResponse_

typedef ::unity_msgs::PoseResponse_<std::allocator<void> > PoseResponse;

typedef boost::shared_ptr< ::unity_msgs::PoseResponse > PoseResponsePtr;
typedef boost::shared_ptr< ::unity_msgs::PoseResponse const> PoseResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::unity_msgs::PoseResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::unity_msgs::PoseResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::unity_msgs::PoseResponse_<ContainerAllocator1> & lhs, const ::unity_msgs::PoseResponse_<ContainerAllocator2> & rhs)
{
  return lhs.output == rhs.output;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::unity_msgs::PoseResponse_<ContainerAllocator1> & lhs, const ::unity_msgs::PoseResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace unity_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::unity_msgs::PoseResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::unity_msgs::PoseResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::unity_msgs::PoseResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::unity_msgs::PoseResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::unity_msgs::PoseResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::unity_msgs::PoseResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::unity_msgs::PoseResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "0689e36df5d12b3591755de018d79aad";
  }

  static const char* value(const ::unity_msgs::PoseResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x0689e36df5d12b35ULL;
  static const uint64_t static_value2 = 0x91755de018d79aadULL;
};

template<class ContainerAllocator>
struct DataType< ::unity_msgs::PoseResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "unity_msgs/PoseResponse";
  }

  static const char* value(const ::unity_msgs::PoseResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::unity_msgs::PoseResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ArmPose output\n"
"\n"
"================================================================================\n"
"MSG: unity_msgs/ArmPose\n"
"float32 q1\n"
"float32 q2\n"
"float32 q3\n"
"float32 d4\n"
"float32 q5\n"
"float32 succ\n"
;
  }

  static const char* value(const ::unity_msgs::PoseResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::unity_msgs::PoseResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.output);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct PoseResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::unity_msgs::PoseResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::unity_msgs::PoseResponse_<ContainerAllocator>& v)
  {
    s << indent << "output: ";
    s << std::endl;
    Printer< ::unity_msgs::ArmPose_<ContainerAllocator> >::stream(s, indent + "  ", v.output);
  }
};

} // namespace message_operations
} // namespace ros

#endif // UNITY_MSGS_MESSAGE_POSERESPONSE_H
