// Generated by gencpp from file unity_msgs/Position.msg
// DO NOT EDIT!


#ifndef UNITY_MSGS_MESSAGE_POSITION_H
#define UNITY_MSGS_MESSAGE_POSITION_H

#include <ros/service_traits.h>


#include <unity_msgs/PositionRequest.h>
#include <unity_msgs/PositionResponse.h>


namespace unity_msgs
{

struct Position
{

typedef PositionRequest Request;
typedef PositionResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct Position
} // namespace unity_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::unity_msgs::Position > {
  static const char* value()
  {
    return "5190f887b70decc2fafe0ae2939b233a";
  }

  static const char* value(const ::unity_msgs::Position&) { return value(); }
};

template<>
struct DataType< ::unity_msgs::Position > {
  static const char* value()
  {
    return "unity_msgs/Position";
  }

  static const char* value(const ::unity_msgs::Position&) { return value(); }
};


// service_traits::MD5Sum< ::unity_msgs::PositionRequest> should match
// service_traits::MD5Sum< ::unity_msgs::Position >
template<>
struct MD5Sum< ::unity_msgs::PositionRequest>
{
  static const char* value()
  {
    return MD5Sum< ::unity_msgs::Position >::value();
  }
  static const char* value(const ::unity_msgs::PositionRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::unity_msgs::PositionRequest> should match
// service_traits::DataType< ::unity_msgs::Position >
template<>
struct DataType< ::unity_msgs::PositionRequest>
{
  static const char* value()
  {
    return DataType< ::unity_msgs::Position >::value();
  }
  static const char* value(const ::unity_msgs::PositionRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::unity_msgs::PositionResponse> should match
// service_traits::MD5Sum< ::unity_msgs::Position >
template<>
struct MD5Sum< ::unity_msgs::PositionResponse>
{
  static const char* value()
  {
    return MD5Sum< ::unity_msgs::Position >::value();
  }
  static const char* value(const ::unity_msgs::PositionResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::unity_msgs::PositionResponse> should match
// service_traits::DataType< ::unity_msgs::Position >
template<>
struct DataType< ::unity_msgs::PositionResponse>
{
  static const char* value()
  {
    return DataType< ::unity_msgs::Position >::value();
  }
  static const char* value(const ::unity_msgs::PositionResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // UNITY_MSGS_MESSAGE_POSITION_H
